package com.pradeep.pixelgrid.ui.theme

import androidx.compose.ui.graphics.Color

// Shadcn Zinc Light Colors
val LightBackground = Color(0xFFFFFFFF)
val LightForeground = Color(0xFF09090B)
val LightCard = Color(0xFFFFFFFF)
val LightCardForeground = Color(0xFF09090B)
val LightPrimary = Color(0xFF18181B)
val LightPrimaryForeground = Color(0xFFFAFAFA)
val LightSecondary = Color(0xFFF4F4F5)
val LightSecondaryForeground = Color(0xFF18181B)
val LightMuted = Color(0xFFF4F4F5)
val LightMutedForeground = Color(0xFF71717A)
val LightAccent = Color(0xFFF4F4F5)
val LightAccentForeground = Color(0xFF18181B)
val LightDestructive = Color(0xFFEF4444)
val LightDestructiveForeground = Color(0xFFFAFAFA)
val LightBorder = Color(0xFFE4E4E7)
val LightInput = Color(0xFFE4E4E7)
val LightRing = Color(0xFF18181B)

// Shadcn Zinc Dark Colors (Deep Slate / Zinc 950)
val DarkBackground = Color(0xFF09090B)
val DarkForeground = Color(0xFFFAFAFA)
val DarkCard = Color(0xFF09090B)
val DarkCardForeground = Color(0xFFFAFAFA)
val DarkPrimary = Color(0xFFFAFAFA)
val DarkPrimaryForeground = Color(0xFF18181B)
val DarkSecondary = Color(0xFF27272A)
val DarkSecondaryForeground = Color(0xFFFAFAFA)
val DarkMuted = Color(0xFF27272A)
val DarkMutedForeground = Color(0xFFA1A1AA)
val DarkAccent = Color(0xFF27272A)
val DarkAccentForeground = Color(0xFFFAFAFA)
val DarkDestructive = Color(0xFF7F1D1D)
val DarkDestructiveForeground = Color(0xFFFAFAFA)
val DarkBorder = Color(0xFF27272A)
val DarkInput = Color(0xFF27272A)
val DarkRing = Color(0xFFD4D4D8)

// Extra accents (e.g. glowing blue selection)
val BlueAccent = Color(0xFF3B82F6)
